# Importing & Loading Data

***1. Import Pandas library***

In [6]:
import pandas as pd

***2. Load CSV file***

In [7]:
df =pd.read_csv('netflix_titles.csv')

***3. Save DataFrame as CSV***

In [8]:
df.to_csv('netflix_cleaned_data.csv',index = False)

***4. Display first 5 rows***

In [9]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

***5. Display last 5 rows***

In [10]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

***6. Random 5 rows***

In [11]:
df.sample()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5225,s5226,Movie,Kingdom of Us,Lucy Cohen,NaN,United Kingdom,"October 13, 2017",2017,TV-MA,110 min,Documentaries,A father's suicide sends a family of eight on ...

***7. Get dataset shape (rows, columns)***

In [12]:
df.shape

(8807, 12)

***8. Get column names***

In [13]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

# Data Inspection

***9.Dataset summary***

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

***10. Summary statistics***

In [15]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

***11. Get data types***

In [16]:
	df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

**12. Check memory usage***

In [17]:
df.memory_usage()

Index             132
show_id         70456
type            70456
title           70456
director        70456
cast            70456
country         70456
date_added      70456
release_year    70456
rating          70456
duration        70456
listed_in       70456
description     70456
dtype: int64

***13. Get index***

In [18]:
df.index

RangeIndex(start=0, stop=8807, step=1)

***14. Count unique values per column***

In [19]:
df.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

***15. Count missing values***

In [20]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

***16. Count duplicate rows***

In [21]:
df.duplicated().sum()

np.int64(0)

***17. Count non-null values per column***

In [22]:
df.count()

show_id         8807
type            8807
title           8807
director        6173
cast            7982
country         7976
date_added      8797
release_year    8807
rating          8803
duration        8804
listed_in       8807
description     8807
dtype: int64

***18. Count occurrences of unique values***

In [23]:
df.value_counts()

show_id  type   title                        director            cast                                                                                                                                                                       country                                        date_added          release_year  rating  duration  listed_in                                           description
s997     Movie  HOMUNCULUS                   Takashi Shimizu     Go Ayano, Ryo Narita, Yukino Kishii, Anna Ishii, Seiyo Uchino                                                                                                              Japan                                          April 22, 2021      2021          TV-MA   116 min   Horror Movies, International Movies, Thrillers      Truth and illusion blurs when a homeless amnesiac awakens from an experimental medical procedure with the ability to see people's innermost traumas.       1
s10      Movie  The Starling                 Theodore Melfi      Melissa McCarthy, Chris O'Dowd, Kevin Kline, Timothy Olyphant, Daveed Diggs, Skyler Gisondo, Laura Harrier, Rosalind Chao, Kimberly Quinn, Loretta Devine, Ravi Kapoor     United States                                  September 24, 2021  2021          PG-13   104 min   Comedies, Dramas                                    A woman adjusting to life after a loss contends with a feisty bird that's taken over her garden — and a husband who's struggling to find a way forward.    1
s1000    Movie  Stowaway                     Joe Penna           Anna Kendrick, Toni Collette, Daniel Dae Kim, Shamier Anderson                                                                                                             Germany, United States                         April 22, 2021      2021          TV-MA   116 min   Dramas, International Movies, Thrillers             A three-person crew on a mission to Mars faces an impossible choice when an unplanned passenger jeopardizes the lives of everyone on board.                1
s1002    Movie  Oloibiri                     Curtis Graham       Olu Jacobs, Richard Mofe-Damijo, William R. Moses, Taiwo Ajai-Lycett, Ifeanyi Williams, Ivie Okujaye, Dayton Sinkia, Bradley Gordon                                        Canada, Nigeria, United States                 April 21, 2021      2015          TV-14   86 min    Dramas, International Movies, Thrillers             After drilling depletes a small village, a corporation finds more oil in the region, igniting tensions among the community.                                1
s978     Movie  Dedemin Fisi                 Meltem Bozoflu      Onur Buldu, Alper Kul, Erdem Yener, Onur Atilla, Özge Borak, Doğa Rutkay, Meltem Yılmazkaya, İrem Sak                                                                      Turkey                                         April 23, 2021      2016          TV-14   101 min   Comedies, International Movies                      When a brain-dead family patriarch is about to be taken off life support, his extended family gathers round and plots to see who'll get his money.         1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ..
s1019    Movie  Jaane Tu... Ya Jaane Na      Abbas Tyrewala      Imran Khan, Genelia D'Souza, Manjari Fadnis, Ayaz Khan, Prateik Babbar, Ratna Pathak Shah, Arbaaz Khan, Sohail Khan                                                        India                                          April 17, 2021      2008          TV-14   147 min   Comedies, International Movies, Music & Musicals    Soft-spoken Jai and spitfire beauty Aditi couldn't be more different – but their family and friends know that they're a perfect match.                     1
s1018    Movie  Dhobi Ghat (Mumbai Diaries)  Kiran Rao           Aamir Khan, Monica Dogra, Kriti Malhotra, Prateik Babbar, Aasha Pawar, Jyoti Pawar, Norma Lobo, Kitu Gidwani, Danish Husain, Jehan Manekshaw                               India                                          April 17, 2021      2010          TV-MA   102 min   Dramas, International Movies                        In this intimate drama, circumstances draw together four people from different castes – which would normally preclude them from forming friendships.       1
s1017    Movie  Delhi Belly                  Abhinay Deo         Imran Khan, Vir Das, Kunaal Roy Kapur, Poorna Jagannathan, Shenaz Treasury, Vijay Raaz, Paresh Ganatra, Rahul Singh                                                        India                                          April 17, 2021      2011          TV-MA   101 min   Action & Adventure, Comedies, International Movies  Three flatmates get involved in the shady business belonging to one roomie's fiancé, and discover that a global crime syndicate is gunning for them.       1
s1016    Movie  American Me                  Edward James Olmos  Edward James Olmos, William Forsythe, Pepe Serna, Danny De La Paz, Evelina Fernandez, Cary-Hiroyuki Tagawa, Daniel Villarreal, Sal Lopez, Daniel Haro, Domingo Ambriz      United States                                  April 17, 2021      1992          R       126 min   Dramas                                              Three friends born in poverty create their own capitalist dream as powerful gang members. Time in prison makes one of them consider a fresh beginning.     1
s1014    Movie  Miss Sloane                  John Madden         Jessica Chastain, Mark Strong, Gugu Mbatha-Raw, Michael Stuhlbarg, Raoul Bhaneja, John Lithgow, Sam Waterston, Chuck Shamata, Jake Lacy, Alison Pill, David Wilson Barnes  France, United States, United Kingdom, Canada  April 19, 2021      2016          R       132 min   Thrillers                                           A tenacious Capitol Hill lobbyist with a well-earned reputation for winning takes on the most challenging battle of her career.                            1
Name: count, Length: 5332, dtype: int64

# Handling Missing Values

***19. Drop missing values***

In [24]:
df.dropna(inplace = True)

***20. Replace specific values***

In [25]:
df.replace({"NA": None})

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

# Filtering & Selecting Data

***21. Select specific columns***

In [26]:
df[["type","country"]]

         type                                            country
7       Movie  United States, Ghana, Burkina Faso, United Kin...
8     TV Show                                     United Kingdom
9       Movie                                      United States
12      Movie                            Germany, Czech Republic
24      Movie                                              India
...       ...                                                ...
8801    Movie                       United Arab Emirates, Jordan
8802    Movie                                      United States
8804    Movie                                      United States
8805    Movie                                      United States
8806    Movie                                              India

[5332 rows x 2 columns]

***22. Select row by index***

In [27]:
df.iloc[5]

show_id                                                       s28
type                                                        Movie
title                                                   Grown Ups
director                                             Dennis Dugan
cast            Adam Sandler, Kevin James, Chris Rock, David S...
country                                             United States
date_added                                     September 20, 2021
release_year                                                 2010
rating                                                      PG-13
duration                                                  103 min
listed_in                                                Comedies
description     Mourning the loss of their beloved junior high...
Name: 27, dtype: object

***23. Filter rows where release_year = 2021***

In [28]:
df.loc[df["release_year"]==2021]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
81,s82,Movie,Kate,Cedric Nicolas-Troyan,"Mary Elizabeth Winstead, Jun Kunimura, Woody H...",United States,"September 10, 2021",2021,R,106 min,Action & Adventure,"Slipped a fatal poison on her final job, a rut..."
190,s191,Movie,Thimmarusu,Sharan Koppisetty,"Satya Dev, Priyanka Jawalkar, Brahmaji",India,"August 28, 2021",2021,TV-14,125 min,"Dramas, International Movies",Eight years after a young man is framed for mu...
...,...,...,...,...,...,...,...,...,...,...,...,...
1411,s1412,Movie,What Would Sophia Loren Do?,Ross Kauffman,"Nancy ""Vincenza Careri"" Kulik, Sophia Loren",United States,"January 15, 2021",2021,TV-14,32 min,Documentaries,"In this delightful short documentary, an Itali..."
1412,s1413,Movie,Wish You,Sung Do-jun,"Kang In-soo, Lee Sang, Soo-bin",South Korea,"January 15, 2021",2021,TV-PG,102 min,"Dramas, International Movies, LGBTQ Movies","Singing and dreaming together, a talented sing..."
1424,s1425,Movie,Charming,Ross Venokur,"Wilmer Valderrama, Demi Lovato, Sia, Nia Varda...","Canada, United States, Cayman Islands","January 8, 2021",2021,TV-Y7,85 min,"Children & Family Movies, Comedies","On the eve of his 21st birthday, an adored pri..."
1432,s1433,TV Show,The Idhun Chronicles,Maite Ruiz De Austri,"Michelle Jenner, Itzan Escamilla, Sergio Mur, ...",Spain,"January 8, 2021",2021,TV-14,2 Seasons,"Anime Series, International TV Shows, Spanish-...",A boy suddenly orphaned fights his parents' ki...
1468,s1469,Movie,What Happened to Mr. Cha?,Kim Dong-kyu,"Cha In-pyo, Cho Dal-hwan, Song Jae-ryong",South Korea,"January 1, 2021",2021,TV-MA,102 min,"Comedies, International Movies","With the peak of his career long behind him, a..."

***24. Multiple conditions***

In [29]:
df.loc[(df["type"] == "Movie") & (df["country"] == "south korea")]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

***25. Filter with isin()***

In [30]:
df[df["country"].isin(["United States", "South Korea"])]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...
28,s29,Movie,Dark Skies,Scott Stewart,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,97 min,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...
41,s42,Movie,Jaws,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...",United States,"September 16, 2021",1975,PG,124 min,"Action & Adventure, Classic Movies, Dramas",When an insatiable great white shark terrorize...
42,s43,Movie,Jaws 2,Jeannot Szwarc,"Roy Scheider, Lorraine Gary, Murray Hamilton, ...",United States,"September 16, 2021",1978,PG,116 min,"Dramas, Horror Movies, Thrillers",Four years after the last deadly shark attacks...
...,...,...,...,...,...,...,...,...,...,...,...,...
8791,s8792,Movie,Young Adult,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,94 min,"Comedies, Dramas, Independent Movies",When a divorced writer gets a letter from an o...
8793,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,"Dennis Quaid, Rene Russo, Sean Faris, Katija P...",United States,"November 20, 2019",2005,PG,88 min,"Children & Family Movies, Comedies",When a father of eight and a mother of 10 prep...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."

***26. Select specific rows & columns using index***

In [31]:
df.iloc[0:10, 2:5]

,title,director,cast
7,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D..."
8,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho..."
9,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T..."
12,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ..."
24,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi..."
27,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S..."
28,Dark Skies,Scott Stewart,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak..."
29,Paranoia,Robert Luketic,"Liam Hemsworth, Gary Oldman, Amber Heard, Harr..."
38,Birth of the Dragon,George Nolfi,"Billy Magnussen, Ron Yuan, Qu Jingjing, Terry ..."
41,Jaws,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L..."

***27. Get value at a specific row & columnGet value at a specific row & column***

In [32]:
df.iloc[3, df.columns.get_loc("title")]

'Je Suis Karl'

***28. Get unique values***

In [33]:
df["title"].unique()

array(['Sankofa', 'The Great British Baking Show', 'The Starling', ...,
       'Zombieland', 'Zoom', 'Zubaan'], dtype=object)

***29. Count unique values***

In [34]:
df["title"].nunique()

5332

# Sorting & Ordering Data

***30. Sort by rating***

In [35]:
df.sort_values(by="rating", ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7988,s7989,Movie,Sex Doll,Sylvie Verheyde,"Hafsia Herzi, Ash Stymest, Karole Rocher, Paul...","United Kingdom, France","July 10, 2017",2016,UR,103 min,"Dramas, International Movies, Romantic Movies",A high-end call girl falls for a handsome man ...
8790,s8791,Movie,You Don't Mess with the Zohan,Dennis Dugan,"Adam Sandler, John Turturro, Emmanuelle Chriqu...",United States,"September 1, 2019",2008,UR,113 min,"Action & Adventure, Comedies",An Israeli counterterrorism soldier with a sec...
7058,s7059,Movie,Immoral Tales,Walerian Borowczyk,"Lise Danvers, Fabrice Luchini, Charlotte Alexa...",France,"June 6, 2019",1974,UR,103 min,"Dramas, International Movies, Romantic Movies",This anthology illustrates the timeless nature...
6581,s6582,Movie,Dear Dracula,Chad Van De Keere,"Nathan Gamble, Ray Liotta, Emilio Estevez, Ari...",United States,"February 18, 2016",2012,TV-Y7-FV,43 min,"Children & Family Movies, Comedies",When he gets a fan letter from a young monster...
7513,s7514,Movie,Motu Patlu: King of Kings,Suhas Kadav,"Saurav Chakrabarty, Vinay Pathak",India,"July 6, 2017",2016,TV-Y7-FV,109 min,"Children & Family Movies, Comedies",Motu and Patlu want to help a circus lion get ...
...,...,...,...,...,...,...,...,...,...,...,...,...
7154,s7155,Movie,Justin Bieber: Never Say Never,Jon M. Chu,"Justin Bieber, Ludacris, Usher Raymond, Jaden ...",United States,"January 1, 2018",2011,G,106 min,"Documentaries, Music & Musicals",Teen idol Justin Bieber provides personal snap...
6151,s6152,Movie,An American Tail,Don Bluth,"Erica Yohn, Nehemiah Persoff, Amy Green, Phill...",United States,"April 1, 2018",1986,G,80 min,Children & Family Movies,"Fievel, a young Russian mouse, immigrates to A..."
6152,s6153,Movie,An American Tail: Fievel Goes West,"Phil Nibbelink, Simon Wells","Philip Glasser, James Stewart, Erica Yohn, Cat...",United States,"April 1, 2018",1991,G,75 min,Children & Family Movies,Fievel and his family head west for what turns...
6153,s6154,Movie,An American Tail: The Mystery of the Night Mon...,Larry Latham,"Thomas Dekker, Lacey Chabert, Jane Singer, Neh...",United States,"April 1, 2018",1999,G,75 min,Children & Family Movies,When a monster goes on a mouse-napping spree i...
6781,s6782,Movie,For the Love of Benji,Joe Camp,"Patsy Garrett, Cynthia Smith, Allen Fiuzat, Ed...",United States,"March 6, 2018",1977,G,84 min,Children & Family Movies,Benji and his owner get separated in Greece. O...

***31. Multi-column sort***

In [36]:
df.sort_values(by=["release_year", "country"], ascending=[True, False])

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8640,s8641,Movie,Tunisian Victory,"Frank Capra, John Huston, Hugh Stewart, Roy Bo...",Burgess Meredith,"United States, United Kingdom","March 31, 2017",1944,TV-14,76 min,"Classic Movies, Documentaries",British and American troops join forces to lib...
7219,s7220,Movie,Know Your Enemy - Japan,"Frank Capra, Joris Ivens","Walter Huston, Dana Andrews",United States,"March 31, 2017",1945,TV-14,63 min,"Classic Movies, Documentaries",Though culturally insensitive by modern standa...
7294,s7295,Movie,Let There Be Light,John Huston,Walter Huston,United States,"March 31, 2017",1946,TV-PG,58 min,"Classic Movies, Documentaries",Some returning combat veterans suffer scars th...
8587,s8588,Movie,Thunderbolt,"William Wyler, John Sturges","James Stewart, Lloyd Bridges",United States,"March 31, 2017",1947,TV-PG,42 min,"Classic Movies, Documentaries",A P-47 Thunderbolt squadron is shown in prepar...
...,...,...,...,...,...,...,...,...,...,...,...,...
1258,s1259,Movie,Bigfoot Family,"Jérémie Degruson, Ben Stassen","Jules Wojciechowski, Roger Craig Smith, Grant ...","Belgium, France","February 26, 2021",2021,TV-Y7,88 min,"Children & Family Movies, Comedies",Bigfoot’s now a big deal. So when he goes miss...
1378,s1379,Movie,Penguin Bloom,Glendyn Ivin,"Naomi Watts, Andrew Lincoln, Jacki Weaver, Gri...","Australia, United States","January 27, 2021",2021,TV-14,95 min,"Children & Family Movies, Dramas",As a mom copes with the aftermath of a harrowi...
393,s394,Movie,A Second Chance: Rivals!,Clay Glen,"Emily Morris, Stella Shute, Eva Grados, India ...",Australia,"July 23, 2021",2021,PG,91 min,"Children & Family Movies, Sports Movies",Crushed when she doesn't qualify for the Olymp...
506,s507,Movie,This Little Love Of Mine,Christine Luby,"Saskia Hampele, Liam McIntyre, Lynn Gilmartin,...",Australia,"July 7, 2021",2021,TV-G,92 min,"International Movies, Romantic Movies",A workaholic lawyer returns to her island home...
838,s839,Movie,Soy Rada: Serendipity,Pablo Faro,Agustín Aristarán,Argentina,"May 27, 2021",2021,TV-MA,70 min,Stand-Up Comedy,The delightful Argentine comic Agustín Aristar...

***32. Sort by index***

In [37]:
df.sort_index()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

***33. Reset index***

In [38]:
df.reset_index(drop=True, inplace=True)

***34. Rename index***

In [39]:
df.index.show_id = "ID"

# Grouping & Aggregation

***35. Summary statistics per group***

In [40]:
df.groupby("rating").describe()

         release_year                                                   \
                count         mean        std     min      25%     50%
rating
G                40.0  1997.250000  18.327155  1956.0  1988.25  2002.5
NC-17             2.0  2013.500000   0.707107  2013.0  2013.25  2013.5
NR               58.0  2009.948276  11.840197  1958.0  2011.25  2015.0
PG              275.0  2008.127273  11.753326  1973.0  2004.00  2011.0
PG-13           470.0  2009.178723   8.945343  1955.0  2005.00  2011.0
R               778.0  2010.341902  10.003413  1962.0  2007.00  2014.0
TV-14          1214.0  2012.218287  10.630927  1942.0  2011.00  2016.0
TV-G             84.0  2015.297619   9.063072  1954.0  2015.00  2017.0
TV-MA          1822.0  2015.909440   6.028309  1963.0  2016.00  2017.0
TV-PG           431.0  2012.106729  11.644251  1946.0  2011.00  2016.0
TV-Y             76.0  2016.881579   3.773476  2003.0  2015.00  2018.0
TV-Y7            76.0  2015.881579   3.622033  2006.0  2013.00  2016.0
TV-Y7-FV          3.0  2013.666667   2.081666  2012.0  2012.50  2013.0
UR                3.0  1999.333333  22.300972  1974.0  1991.00  2008.0


              75%     max
rating
G         2009.50  2019.0
NC-17     2013.75  2014.0
NR        2016.00  2018.0
PG        2017.00  2021.0
PG-13     2016.00  2021.0
R         2017.00  2021.0
TV-14     2018.00  2021.0
TV-G      2019.25  2021.0
TV-MA     2019.00  2021.0
TV-PG     2018.00  2021.0
TV-Y      2020.00  2021.0
TV-Y7     2019.00  2021.0
TV-Y7-FV  2014.50  2016.0
UR        2012.00  2016.0

***36. Count number of rows per segment***

In [41]:
	df.groupby("title").size()

title
#Alive                           1
#AnneFrank - Parallel Stories    1
#FriendButMarried                1
#FriendButMarried 2              1
#Roxy                            1
                                ..
​Goli Soda 2                     1
​Maj Rati ​​Keteki               1
​Mayurakshi                      1
​​Kuch Bheege Alfaaz             1
반드시 잡는다                          1
Length: 5332, dtype: int64

***37. Get first row of each group***

In [42]:
	df.groupby("title").first()

,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
title,,,,,,,,,,,
#Alive,s2037,Movie,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,"September 8, 2020",2020,TV-MA,99 min,"Horror Movies, International Movies, Thrillers","As a grisly virus rampages a city, a lone man ..."
#AnneFrank - Parallel Stories,s2305,Movie,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,95 min,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol..."
#FriendButMarried,s2482,Movie,Rako Prijanto,"Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...",Indonesia,"May 21, 2020",2018,TV-G,102 min,"Dramas, International Movies, Romantic Movies","Pining for his high school crush for years, a ..."
#FriendButMarried 2,s2325,Movie,Rako Prijanto,"Adipati Dolken, Mawar de Jongh, Sari Nila, Von...",Indonesia,"June 28, 2020",2020,TV-G,104 min,"Dramas, International Movies, Romantic Movies",As Ayu and Ditto finally transition from best ...
#Roxy,s5974,Movie,Michael Kennedy,"Jake Short, Sarah Fisher, Booboo Stewart, Dann...",Canada,"April 10, 2019",2018,TV-14,105 min,"Comedies, Romantic Movies",A teenage hacker with a huge nose helps a cool...
...,...,...,...,...,...,...,...,...,...,...,...
​Goli Soda 2,s5969,Movie,Vijay Milton,"Samuthirakani, Bharath Seeni, Vinoth, Esakki B...",India,"September 15, 2018",2018,TV-14,128 min,"Action & Adventure, Dramas, International Movies","A taxi driver, a gangster and an athlete strug..."
​Maj Rati ​​Keteki,s5970,Movie,Santwana Bardoloi,"Adil Hussain, Shakil Imtiaz, Mahendra Rabha, S...",India,"September 15, 2018",2017,TV-14,117 min,"Dramas, International Movies",A successful writer returns to the town that l...
​Mayurakshi,s5971,Movie,Atanu Ghosh,"Soumitra Chatterjee, Prasenjit Chatterjee, Ind...",India,"September 15, 2018",2017,TV-14,100 min,"Dramas, International Movies",When a middle-aged divorcee returns to Kolkata...
​​Kuch Bheege Alfaaz,s4668,Movie,Onir,"Geetanjali Thapa, Zain Khan Durrani, Shray Rai...",India,"September 1, 2018",2018,TV-14,110 min,"Dramas, Independent Movies, International Movies",After accidentally connecting over the Interne...
반드시 잡는다,s5023,Movie,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...

***38. Get last row of each group***

In [43]:
df.groupby("rating").last()

,show_id,type,title,director,cast,country,date_added,release_year,duration,listed_in,description
rating,,,,,,,,,,,
G,s8746,Movie,Willy Wonka & the Chocolate Factory,Mel Stuart,"Gene Wilder, Jack Albertson, Peter Ostrum, Roy...","United States, East Germany, West Germany","January 1, 2020",1971,100 min,"Children & Family Movies, Classic Movies, Come...",Zany Willy Wonka causes a stir when he announc...
NC-17,s6339,Movie,Blue Is the Warmest Color,Abdellatif Kechiche,"Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...","France, Belgium, Spain","August 26, 2016",2013,180 min,"Dramas, Independent Movies, International Movies","Determined to fall in love, 15-year-old Adele ..."
NR,s8793,Movie,Young Tiger,Mu Chu,"Qiu Yuen, Charlie Chin, Jackie Chan, Hu Chin, ...",Hong Kong,"November 1, 2016",1973,81 min,"Action & Adventure, International Movies","Aided only by a tough female police officer, a..."
PG,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
PG-13,s8783,Movie,Yoga Hosers,Kevin Smith,"Harley Quinn Smith, Lily-Rose Depp, Johnny Dep...",United States,"December 2, 2016",2016,88 min,"Comedies, Horror Movies, Independent Movies",With an all-important high school party at sta...
R,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
TV-14,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
TV-G,s8787,Movie,You Can Tutu,James Brown,"Lily O'Regan, Jeannettsy Enriquez Borges, Joel...",United Kingdom,"December 31, 2017",2017,87 min,Children & Family Movies,A gifted young ballet dancer struggles to find...
TV-MA,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
TV-PG,s8790,Movie,You Changed My Life,Cathy Garcia-Molina,"John Lloyd Cruz, Sarah Geronimo, Rayver Cruz, ...",Philippines,"February 27, 2019",2009,116 min,"Comedies, Dramas, International Movies",Laida and Miggy think they've found perfect ha...
TV-Y,s8008,Movie,Shopkins: World Vacation,Richard Bailey,"Kate Murphy, Cassandra Morris, Erika Harlacher...",Australia,"November 15, 2018",2017,71 min,Movies,The Shopkins and Shoppies jet around the world...
TV-Y7,s8782,Movie,Yo-Kai Watch: The Movie,Mark Risley,"Johnny Yong Bosch, Joey D'Auria, Alicyn Packar...","Japan, United States","December 1, 2016",2016,96 min,"Anime Features, Children & Family Movies",Nate's special Yo-Kai Watch is missing. He tra...
TV-Y7-FV,s7514,Movie,Motu Patlu: King of Kings,Suhas Kadav,"Saurav Chakrabarty, Vinay Pathak",India,"July 6, 2017",2016,109 min,"Children & Family Movies, Comedies",Motu and Patlu want to help a circus lion get ...
UR,s8791,Movie,You Don't Mess with the Zohan,Dennis Dugan,"Adam Sandler, John Turturro, Emmanuelle Chriqu...",United States,"September 1, 2019",2008,113 min,"Action & Adventure, Comedies",An Israeli counterterrorism soldier with a sec...

***39. Rank within each group***

In [44]:
df.groupby("rating").rank()

,show_id,type,title,director,cast,country,date_added,release_year,duration,listed_in,description
0,1646.0,871.0,1274.0,577.0,925.0,1802.0,1783.0,37.0,647.0,863.5,1185.0
1,1204.0,1196.0,1028.0,101.0,697.0,1007.0,1189.0,1195.5,1006.5,203.0,202.0
2,1.0,235.5,408.0,442.0,304.0,257.0,461.0,466.5,50.0,197.0,84.0
3,51.0,871.0,764.0,303.0,1023.0,336.0,1779.0,1787.0,672.0,1051.5,440.0
4,241.0,589.0,489.0,906.0,833.0,453.5,1188.0,103.0,763.5,533.0,1148.0
...,...,...,...,...,...,...,...,...,...,...,...
5327,1792.0,871.0,1812.0,995.0,90.0,1148.0,1253.0,379.0,1678.5,1244.0,1238.0
5328,760.0,389.5,776.0,165.0,495.0,466.0,631.5,194.5,444.0,384.0,110.0
5329,761.0,389.5,777.0,646.5,350.0,466.0,593.5,233.0,527.0,341.0,507.0
5330,272.0,138.0,275.0,190.0,257.0,148.5,89.0,81.5,155.0,107.5,94.0
5331,1202.0,589.0,1207.0,701.0,1153.0,453.5,774.5,518.0,211.5,915.5,173.0

# Merging, Joining & Concatenation

In [45]:



# Netflix dataset (df1)
df1 = pd.DataFrame({
    "show_id": ["s1", "s2", "s3", "s4"],
    "title": ["Inception", "Titanic", "Interstellar", "Avatar"],
    "release_year": [2010, 1997, 2014, 2009],
    "country": ["USA", "USA", "SOUTH KOREA", "INDIA"],
    "rating": ["PG-13", "PG-13", "PG-13", "PG-13"]
})

# Ratings dataset (df2)
df2 = pd.DataFrame({
    "title": ["Inception", "Titanic", "Interstellar", "The Matrix"],
    "average_rating": [8.8, 7.8, 8.6, 8.7],
    "country": ["USA", "USA", "SOUTH KOREA", "INDIA"],
    "total_reviews": [1200000, 900000, 1100000, 1500000]
})

***40. Merge datasets***

In [46]:
df_merged = df1.merge(df2, on="title", how="inner")

print(df_merged)

  show_id         title  release_year    country_x rating  average_rating  \
0      s1     Inception          2010          USA  PG-13             8.8
1      s2       Titanic          1997          USA  PG-13             7.8
2      s3  Interstellar          2014  SOUTH KOREA  PG-13             8.6

     country_y  total_reviews
0          USA        1200000
1          USA         900000
2  SOUTH KOREA        1100000

***41. Left join***

In [47]:
df_merged=df1.merge(df2, on= "title", how="left")
print(df_merged)

  show_id         title  release_year    country_x rating  average_rating  \
0      s1     Inception          2010          USA  PG-13             8.8
1      s2       Titanic          1997          USA  PG-13             7.8
2      s3  Interstellar          2014  SOUTH KOREA  PG-13             8.6
3      s4        Avatar          2009        INDIA  PG-13             NaN

     country_y  total_reviews
0          USA      1200000.0
1          USA       900000.0
2  SOUTH KOREA      1100000.0
3          NaN            NaN

***42. Append rows***

In [48]:
df_combined = pd.concat([df1, df2], ignore_index=True)
print(df_combined)

  show_id         title  release_year      country rating  average_rating  \
0      s1     Inception        2010.0          USA  PG-13             NaN
1      s2       Titanic        1997.0          USA  PG-13             NaN
2      s3  Interstellar        2014.0  SOUTH KOREA  PG-13             NaN
3      s4        Avatar        2009.0        INDIA  PG-13             NaN
4     NaN     Inception           NaN          USA    NaN             8.8
5     NaN       Titanic           NaN          USA    NaN             7.8
6     NaN  Interstellar           NaN  SOUTH KOREA    NaN             8.6
7     NaN    The Matrix           NaN        INDIA    NaN             8.7

   total_reviews
0            NaN
1            NaN
2            NaN
3            NaN
4      1200000.0
5       900000.0
6      1100000.0
7      1500000.0

***43. Convert columns to rows***

In [49]:
df.stack()

0     show_id                                                        s8
      type                                                        Movie
      title                                                     Sankofa
      director                                             Haile Gerima
      cast            Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
                                            ...
5331  release_year                                                 2015
      rating                                                      TV-14
      duration                                                  111 min
      listed_in          Dramas, International Movies, Music & Musicals
      description     A scrappy but poor boy worms his way into a ty...
Length: 63984, dtype: object

***44. Convert rows to columns***

In [50]:
df.unstack()

show_id      0                                                      s8
             1                                                      s9
             2                                                     s10
             3                                                     s13
             4                                                     s25
                                           ...
description  5327    Recovering alcoholic Talal wakes up inside a s...
             5328    A political cartoonist, a crime reporter and a...
             5329    Looking to survive in a world taken over by zo...
             5330    Dragged from civilian life, a former superhero...
             5331    A scrappy but poor boy worms his way into a ty...
Length: 63984, dtype: object

# Pivot Tables & Crosstab

***45. Pivot table***

In [51]:
df.pivot_table(
    index=["type", "country"],  # Grouping by type and country
    values="release_year",      # The column to aggregate
    aggfunc="sum"               # Aggregation function
)

                                                            release_year
type    country
Movie   , France, Algeria                                           2014
        Argentina                                                  68485
        Argentina, Brazil, France, Poland, Germany, Den...          2017
        Argentina, Chile                                            4023
        Argentina, Chile, Peru                                      2015
...                                                                  ...
TV Show United Kingdom, United States, Spain, Germany, ...          2011
        United States                                              54458
        United States, Canada                                       4038
        United States, Ireland                                      2016
        United States, Israel, Italy, South Africa                  2013

[637 rows x 1 columns]

***46. Crosstab***

In [52]:
pd.crosstab(df["type"], df["country"])

country,", France, Algeria",Argentina,"Argentina, Brazil, France, Poland, Germany, Denmark","Argentina, Chile","Argentina, Chile, Peru","Argentina, France","Argentina, France, United States, Germany, Qatar","Argentina, Spain","Argentina, United States","Argentina, Uruguay, Serbia",...,"United States, United Kingdom, Spain, South Korea",Uruguay,"Uruguay, Argentina","Uruguay, Argentina, Germany, Spain","Uruguay, Argentina, Spain","Uruguay, Guatemala","Uruguay, Spain, Mexico",Venezuela,Vietnam,Zimbabwe
type,,,,,,,,,,,,,,,,,,,,,
Movie,1,34,1,2,1,1,1,7,1,1,...,1,2,1,1,1,1,1,1,7,1
TV Show,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

***47. Pivot***

In [53]:
df.pivot(index="show_id", columns="type", values="release_year")

type      Movie  TV Show
show_id
s10      2021.0      NaN
s1000    2021.0      NaN
s1002    2015.0      NaN
s1003    2021.0      NaN
s1014    2016.0      NaN
...         ...      ...
s991     2015.0      NaN
s992     2020.0      NaN
s995     2020.0      NaN
s996     2001.0      NaN
s997     2021.0      NaN

[5332 rows x 2 columns]

***48. Unpivot***

In [54]:
df.melt(id_vars=["show_id"], value_vars=["type", "country", "release_year"])

      show_id      variable    value
0          s8          type    Movie
1          s9          type  TV Show
2         s10          type    Movie
3         s13          type    Movie
4         s25          type    Movie
...       ...           ...      ...
15991   s8802  release_year     2015
15992   s8803  release_year     2007
15993   s8805  release_year     2009
15994   s8806  release_year     2006
15995   s8807  release_year     2015

[15996 rows x 3 columns]

***49. Transpose dataset***

In [55]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,5322,5323,5324,5325,5326,5327,5328,5329,5330,5331
show_id,s8,s9,s10,s13,s25,s28,s29,s30,s39,s42,...,s8793,s8794,s8795,s8799,s8800,s8802,s8803,s8805,s8806,s8807
type,Movie,TV Show,Movie,Movie,Movie,Movie,Movie,Movie,Movie,Movie,...,Movie,Movie,Movie,Movie,Movie,Movie,Movie,Movie,Movie,Movie
title,Sankofa,The Great British Baking Show,The Starling,Je Suis Karl,Jeans,Grown Ups,Dark Skies,Paranoia,Birth of the Dragon,Jaws,...,Young Tiger,"Yours, Mine and Ours",اشتباك,Zed Plus,Zenda,Zinzana,Zodiac,Zombieland,Zoom,Zubaan
director,Haile Gerima,Andy Devonshire,Theodore Melfi,Christian Schwochow,S. Shankar,Dennis Dugan,Scott Stewart,Robert Luketic,George Nolfi,Steven Spielberg,...,Mu Chu,Raja Gosnell,Mohamed Diab,Chandra Prakash Dwivedi,Avadhoot Gupte,Majid Al Ansari,David Fincher,Ruben Fleischer,Peter Hewitt,Mozez Singh
cast,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...","Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...","Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...","Adam Sandler, Kevin James, Chris Rock, David S...","Keri Russell, Josh Hamilton, J.K. Simmons, Dak...","Liam Hemsworth, Gary Oldman, Amber Heard, Harr...","Billy Magnussen, Ron Yuan, Qu Jingjing, Terry ...","Roy Scheider, Robert Shaw, Richard Dreyfuss, L...",...,"Qiu Yuen, Charlie Chin, Jackie Chan, Hu Chin, ...","Dennis Quaid, Rene Russo, Sean Faris, Katija P...","Nelly Karim, Hany Adel, Tarek Abdel Aziz, Ahme...","Adil Hussain, Mona Singh, K.K. Raina, Sanjay M...","Santosh Juvekar, Siddharth Chandekar, Sachit P...","Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...","Jesse Eisenberg, Woody Harrelson, Emma Stone, ...","Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...","Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan..."
country,"United States, Ghana, Burkina Faso, United Kin...",United Kingdom,United States,"Germany, Czech Republic",India,United States,United States,"United States, India, France","China, Canada, United States",United States,...,Hong Kong,United States,"Egypt, France",India,India,"United Arab Emirates, Jordan",United States,United States,United States,India
date_added,"September 24, 2021","September 24, 2021","September 24, 2021","September 23, 2021","September 21, 2021","September 20, 2021","September 19, 2021","September 19, 2021","September 16, 2021","September 16, 2021",...,"November 1, 2016","November 20, 2019","October 11, 2018","December 31, 2019","February 15, 2018","March 9, 2016","November 20, 2019","November 1, 2019","January 11, 2020","March 2, 2019"
release_year,1993,2021,2021,2021,1998,2010,2013,2013,2017,1975,...,1973,2005,2016,2014,2009,2015,2007,2009,2006,2015
rating,TV-MA,TV-14,PG-13,TV-MA,TV-14,PG-13,PG-13,PG-13,PG-13,PG,...,NR,PG,TV-14,TV-MA,TV-14,TV-MA,R,R,PG,TV-14
duration,125 min,9 Seasons,104 min,127 min,166 min,103 min,97 min,106 min,96 min,124 min,...,81 min,88 min,98 min,131 min,120 min,96 min,158 min,88 min,88 min,111 min
listed_in,"Dramas, Independent Movies, International Movies","British TV Shows, Reality TV","Comedies, Dramas","Dramas, International Movies","Comedies, International Movies, Romantic Movies",Comedies,"Horror Movies, Sci-Fi & Fantasy",Thrillers,"Action & Adventure, Dramas","Action & Adventure, Classic Movies, Dramas",...,"Action & Adventure, International Movies","Children & Family Movies, Comedies","Dramas, Independent Movies, International Movies","Comedies, Dramas, International Movies","Dramas, International Movies","Dramas, International Movies, Thrillers","Cult Movies, Dramas, Thrillers","Comedies, Horror Movies","Children & Family Movies, Comedies","Dramas, International Movies, Music & Musicals"
description,"On a photo shoot in Ghana, an American model s...",A talented batch of amateur bakers face off in...,A woman adjusting to life after a loss contend...,After most of her family is murdered in a terr...,When the father of the man she loves insists t...,Mourning the loss of their beloved junior high...,A family’s idyllic suburban life shatters when...,"Blackmailed by his company's CEO, a low-level ...",A young Bruce Lee angers kung fu traditionalis...,When an insatiable great white shark terrorize...,...,"Aided only by a tough female police officer, a...",When a father of eight and a mother of 10 prep...,Amid the tumult following Egyptian President M...,A philandering small-town mechanic's political...,A change in the leadership of a political part...,Recovering alcoholic Talal wakes up inside a s...,"A political cartoonist, a crime reporter and a...",Looking to survive in a world taken over by zo...,"Dragged from civilian life, a former superhero...",A scrappy but poor boy worms his way into a ty...

# String Operations

***50. Convert to lowercase***

In [56]:
df["country"].str.lower()

0       united states, ghana, burkina faso, united kin...
1                                          united kingdom
2                                           united states
3                                 germany, czech republic
4                                                   india
                              ...
5327                         united arab emirates, jordan
5328                                        united states
5329                                        united states
5330                                        united states
5331                                                india
Name: country, Length: 5332, dtype: object

***51. Convert to uppercase***

In [57]:
df["country"].str.upper()

0       UNITED STATES, GHANA, BURKINA FASO, UNITED KIN...
1                                          UNITED KINGDOM
2                                           UNITED STATES
3                                 GERMANY, CZECH REPUBLIC
4                                                   INDIA
                              ...
5327                         UNITED ARAB EMIRATES, JORDAN
5328                                        UNITED STATES
5329                                        UNITED STATES
5330                                        UNITED STATES
5331                                                INDIA
Name: country, Length: 5332, dtype: object

***52. Convert to title case***

In [58]:
df["title"].str.title()

0                             Sankofa
1       The Great British Baking Show
2                        The Starling
3                        Je Suis Karl
4                               Jeans
                    ...
5327                          Zinzana
5328                           Zodiac
5329                       Zombieland
5330                             Zoom
5331                           Zubaan
Name: title, Length: 5332, dtype: object

***53. Replace values***

In [59]:
df["director"].str.replace("Mr. ", "")

0              Haile Gerima
1           Andy Devonshire
2            Theodore Melfi
3       Christian Schwochow
4                S. Shankar
               ...
5327        Majid Al Ansari
5328          David Fincher
5329        Ruben Fleischer
5330           Peter Hewitt
5331            Mozez Singh
Name: director, Length: 5332, dtype: object

***54. Check for substring***

In [60]:
df["country"].str.contains("South Korea")

0       False
1       False
2       False
3       False
4       False
        ...
5327    False
5328    False
5329    False
5330    False
5331    False
Name: country, Length: 5332, dtype: bool